### ISSUE TITLE
niceday 頁數 Class 應該改成開頭選擇

### ISSUE THREAD

**Issue by cscolabear** [pamcy/Rainy-To-Do-App#2]
https://github.com/pamcy/Rainy-To-Do-App/blob/018609012b424a77c4939c114ba5b625db282588/src/js/scrape-niceday.js#L106

**Comment by pamcy** [comment]
已修改

[DOM‘s CSS Class 改成只取開頭判斷](https://github.com/pamcy/Rainy-To-Do-App/commit/f815736d494e75662e469c6d091c55c92bc3f3ad)
